### ISSUE TITLE
Add Bazaar equipment-pausing feature?

### ISSUE THREAD

**Issue by ZgSvDaCpke479pF6DzfLgMvK9AiyNsgUBKPghdh** [William758/ZetTweaks#1]
Highly appreciating this all-in-one tweak mod, very convenient and highly optimized, was wondering if you could eventually add the 2nd tweak featured in BetterGameplay by XoXFaby, namely the one that pauses your equipment when holding a gesture and in the bazaar? That'd save another plugin slot, seeing as you already took care of the items falling off stage.

**Comment by William758** [comment]
I've gone ahead and made it so that gesture will not activate equipment in the Bazaar. Equipment will still gain charges in there though.

**Comment by ZgSvDaCpke479pF6DzfLgMvK9AiyNsgUBKPghdh** [comment]
That's even better, thanks very much. Splitting the mod was also a smart idea seeing as the initial reception wasn't great.
