### ISSUE TITLE
[Multiplayer Bug] Mod Appears To Not Correctly State Version #

### ISSUE THREAD

**Issue by GalacticRuler** [William758/ZetTweaks#10]
This mod seems to not tell the game its version number correctly or something, causing clients to disconnect when trying to join the character selection screen? happening with the most recent version of this mod.

**Comment by GalacticRuler** [comment]
should state that I'm not a coder nor certain of this, just an observation. Adding this and attempting multiplayer has caused this issue out of nowhere.

**Comment by William758** [comment]
As far as I know, the mod should be adding its name to the modlist. Maybe the kicked client didn't have the same version? I'm not able to test multiplayer currently so I can't really check. What does the kick message say?

**Comment by GalacticRuler** [comment]
Just says that the required version of this mod is 1.1.1
after checking the code on this repository though, the version number in ZetTweaksPlugin.cs is 1.1.0?

**Comment by William758** [comment]
I didn't update the repository after the update. I just downloaded what I uploaded to the mod site and the version is correct (1.1.1). Can I get a log output from the host and client if possible.

**Comment by GalacticRuler** [comment]
[LogOutput.log](https://github.com/William758/ZetTweaks/files/8191425/LogOutput.log)
Host log ^

Client log currently inaccessible (client is asleep), will try to acquire it whenever I can

**Comment by William758** [comment]
I don't see ZetTweaks installed in that log.

**Comment by GalacticRuler** [comment]
Hm, it was prior to that, I'll see about getting it installed with that friend and get you some logs soon

**Comment by GalacticRuler** [comment]
that was...weird

sending them my mods after they deleted *everything* BIX related, fixed the issue????
but they had done that already anyway so

Eugh, modding is annoying sometimes. Apologies for the Issue!
