### ISSUE TITLE
[Mod Compatibility] ShareSuite

### ISSUE THREAD

**Issue by Dave247** [William758/ZetTweaks#11]
When running ZetTweaks along with [ShareSuite ](https://github.com/FunkFrog/RoR2SharedItems) and using their optional money sharing system, their mod will take priority meaning the option to increase the starting money is overwritten. Potentially the multitudes option might also be affected, but I haven't tried it myself  to know for sure.

I've mentioned the incompatibility to the ShareSuite devs in their Discord (FunkFrog and Sipondo) who have said other mods would need to use their class in order for it to work, and how they are happy to be contacted for more info. I get though how it's only a single option it may not really be worth your time to fix.

Mind you, while that is the one incompatibility between the two mods I have noticed, I do wonder if there may be others. For example both mods make a few changes to items and how they drop in the world so I wouldn't be surprised if there was was other options that were also being ignored/overwritten.

**Comment by William758** [comment]
I've gone ahead and added support for ShareSuite in the latest update.

**Comment by Dave247** [comment]
Thanks! I quite like the mod as it has a lot of small but good changes all bundled in together. Next time I play I'll use the updated 1.1.2 version and let you know if I do happen to notice any other oddities.
