### ISSUE TITLE
directorMoney config seems to do nothing

### ISSUE THREAD

**Issue by MeatMorning** [William758/ZetTweaks#13]
Using 5 as multiplier should cause enumerous amount of mobs and bosses to spawn, but it's definetly spawning regular amount of enemies

**Comment by William758** [comment]
I set the multiplier to 50 as a test and got some vagrants to spawn after a minute, so it's still working on my end. If there is still no noticeable difference after you set it to 50 then I'm guessing another mod is interfering with the feature and I'll need a log output to see what happened.

**Comment by MeatMorning** [comment]
I forgor to enable gameplay tweaks module. my bad.
