### ISSUE TITLE
Console spam if in-game profile is not selected

### ISSUE THREAD

**Issue by ed-ict** [William758/ZetTweaks#3]
Hi there! Thanks for the excellent mod. Just thought I'd quickly report that if a profile is not selected when Risk of Rain 2 loads, or if you attempt to select a new or a different profile in the main menu once the game is loaded, the mod spams the console with the following error: 

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
TPDespair.ZetTweaks.TeleShowFix.SetShouldShow () (at <71f2d9374a1b4809a8174a132fd0018b>:IL_0007)
TPDespair.ZetTweaks.ZetTweaksPlugin.Update () (at <71f2d9374a1b4809a8174a132fd0018b>:IL_0023)

I can very easily reproduce this so if there's any further information I can provide please let me know.

**Comment by William758** [comment]
Just released a fix now, thanks for reporting.
