### ISSUE TITLE
tweakBossDropRewards issue

### ISSUE THREAD

**Issue by ZgSvDaCpke479pF6DzfLgMvK9AiyNsgUBKPghdh** [William758/ZetTweaks#4]
It appears that if tweakBossDropRewards is set to true, the Alloy Worship Unit boss unique to Siren's Call will have a rather large chance to drop the Empathy Cores boss item rather than the random legendary item it's supposed to. Is this intended?

**Comment by William758** [comment]
Yeah just checked and it does actually modify the AWU drops. I'm going to say that's not intentional and make the setting not effect the chances if there is a red item in the reward pool.

**Comment by William758** [comment]
Just uploaded a fix.
