### ISSUE TITLE
[Bug?] Equipment Drones Have Constant HP Drain

### ISSUE THREAD

**Issue by GalacticRuler** [William758/ZetTweaks#9]
I'm fairly certain it's this particular mod, but

whenever I buy an equipment drone, it starts dying the second it is purchased no matter what is placed inside it. It's not a slow drain either, it only takes about 4 second to die every time.

Game's currently still going but the log file isn't particularly helpful here since
`[Warning: Unity Log] Animator.GotoState: State could not be found
[Warning: Unity Log] Invalid Layer Index '-1'
[Info   : Unity Log] Zero duration for effect "ChainGunOrbEffect(Clone)"
[Info   : Unity Log] Zero duration for effect "ChainGunOrbEffect(Clone)"
[Info   : Unity Log] Zero duration for effect "ChainGunOrbEffect(Clone)"
[Info   : Unity Log] Zero duration for effect "ChainGunOrbEffect(Clone)"`
this is the exact same set of errors for every time it spawns and dies. I know the zero duration effect is a vanilla error, and I don't think it's the Animator error nor the invalid layer.

**Comment by GalacticRuler** [comment]
if it's not *this* mod, it may possibly be Moffien's No Void Allies mod, but I doubt that

**Comment by William758** [comment]
Yeah, that's my mod. I forgot to disable the decay after I was finished testing the drones being repurchasable and equipment drones dropping their equipment. Just uploaded a patch.

**Comment by GalacticRuler** [comment]
Alrighty; thanks!
